// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/admin.proto

package holtv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/openotters/holt/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminName is the fully-qualified name of the Admin service.
	AdminName = "openotters.holt.v1.Admin"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminListTunnelsProcedure is the fully-qualified name of the Admin's ListTunnels RPC.
	AdminListTunnelsProcedure = "/openotters.holt.v1.Admin/ListTunnels"
	// AdminStopTunnelProcedure is the fully-qualified name of the Admin's StopTunnel RPC.
	AdminStopTunnelProcedure = "/openotters.holt.v1.Admin/StopTunnel"
	// AdminBlockPeerProcedure is the fully-qualified name of the Admin's BlockPeer RPC.
	AdminBlockPeerProcedure = "/openotters.holt.v1.Admin/BlockPeer"
	// AdminUnblockPeerProcedure is the fully-qualified name of the Admin's UnblockPeer RPC.
	AdminUnblockPeerProcedure = "/openotters.holt.v1.Admin/UnblockPeer"
	// AdminListBlockedProcedure is the fully-qualified name of the Admin's ListBlocked RPC.
	AdminListBlockedProcedure = "/openotters.holt.v1.Admin/ListBlocked"
)

// AdminClient is a client for the openotters.holt.v1.Admin service.
type AdminClient interface {
	ListTunnels(context.Context, *connect.Request[v1.ListTunnelsRequest]) (*connect.Response[v1.ListTunnelsResponse], error)
	StopTunnel(context.Context, *connect.Request[v1.StopTunnelRequest]) (*connect.Response[v1.StopTunnelResponse], error)
	// BlockPeer stops a peer's tunnel AND bans its peer id, so it cannot
	// reconnect even with a valid token — versus StopTunnel's plain
	// disconnect. The ban is on the identity, not one specific token:
	// every token whose subject is that id (including ones minted while
	// blocked) is refused until UnblockPeer. Requires the hub to have a
	// blocker configured; otherwise returns Unimplemented.
	BlockPeer(context.Context, *connect.Request[v1.BlockPeerRequest]) (*connect.Response[v1.BlockPeerResponse], error)
	// UnblockPeer lifts a BlockPeer ban so the peer may reconnect. Tokens
	// minted before the block that have not expired become valid again;
	// blocking never invalidates the tokens themselves.
	UnblockPeer(context.Context, *connect.Request[v1.UnblockPeerRequest]) (*connect.Response[v1.UnblockPeerResponse], error)
	// ListBlocked returns the currently-blocked peers (which have no
	// live tunnel to appear in ListTunnels). Empty when no blocker is
	// configured.
	ListBlocked(context.Context, *connect.Request[v1.ListBlockedRequest]) (*connect.Response[v1.ListBlockedResponse], error)
}

// NewAdminClient constructs a client for the openotters.holt.v1.Admin service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminMethods := v1.File_v1_admin_proto.Services().ByName("Admin").Methods()
	return &adminClient{
		listTunnels: connect.NewClient[v1.ListTunnelsRequest, v1.ListTunnelsResponse](
			httpClient,
			baseURL+AdminListTunnelsProcedure,
			connect.WithSchema(adminMethods.ByName("ListTunnels")),
			connect.WithClientOptions(opts...),
		),
		stopTunnel: connect.NewClient[v1.StopTunnelRequest, v1.StopTunnelResponse](
			httpClient,
			baseURL+AdminStopTunnelProcedure,
			connect.WithSchema(adminMethods.ByName("StopTunnel")),
			connect.WithClientOptions(opts...),
		),
		blockPeer: connect.NewClient[v1.BlockPeerRequest, v1.BlockPeerResponse](
			httpClient,
			baseURL+AdminBlockPeerProcedure,
			connect.WithSchema(adminMethods.ByName("BlockPeer")),
			connect.WithClientOptions(opts...),
		),
		unblockPeer: connect.NewClient[v1.UnblockPeerRequest, v1.UnblockPeerResponse](
			httpClient,
			baseURL+AdminUnblockPeerProcedure,
			connect.WithSchema(adminMethods.ByName("UnblockPeer")),
			connect.WithClientOptions(opts...),
		),
		listBlocked: connect.NewClient[v1.ListBlockedRequest, v1.ListBlockedResponse](
			httpClient,
			baseURL+AdminListBlockedProcedure,
			connect.WithSchema(adminMethods.ByName("ListBlocked")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminClient implements AdminClient.
type adminClient struct {
	listTunnels *connect.Client[v1.ListTunnelsRequest, v1.ListTunnelsResponse]
	stopTunnel  *connect.Client[v1.StopTunnelRequest, v1.StopTunnelResponse]
	blockPeer   *connect.Client[v1.BlockPeerRequest, v1.BlockPeerResponse]
	unblockPeer *connect.Client[v1.UnblockPeerRequest, v1.UnblockPeerResponse]
	listBlocked *connect.Client[v1.ListBlockedRequest, v1.ListBlockedResponse]
}

// ListTunnels calls openotters.holt.v1.Admin.ListTunnels.
func (c *adminClient) ListTunnels(ctx context.Context, req *connect.Request[v1.ListTunnelsRequest]) (*connect.Response[v1.ListTunnelsResponse], error) {
	return c.listTunnels.CallUnary(ctx, req)
}

// StopTunnel calls openotters.holt.v1.Admin.StopTunnel.
func (c *adminClient) StopTunnel(ctx context.Context, req *connect.Request[v1.StopTunnelRequest]) (*connect.Response[v1.StopTunnelResponse], error) {
	return c.stopTunnel.CallUnary(ctx, req)
}

// BlockPeer calls openotters.holt.v1.Admin.BlockPeer.
func (c *adminClient) BlockPeer(ctx context.Context, req *connect.Request[v1.BlockPeerRequest]) (*connect.Response[v1.BlockPeerResponse], error) {
	return c.blockPeer.CallUnary(ctx, req)
}

// UnblockPeer calls openotters.holt.v1.Admin.UnblockPeer.
func (c *adminClient) UnblockPeer(ctx context.Context, req *connect.Request[v1.UnblockPeerRequest]) (*connect.Response[v1.UnblockPeerResponse], error) {
	return c.unblockPeer.CallUnary(ctx, req)
}

// ListBlocked calls openotters.holt.v1.Admin.ListBlocked.
func (c *adminClient) ListBlocked(ctx context.Context, req *connect.Request[v1.ListBlockedRequest]) (*connect.Response[v1.ListBlockedResponse], error) {
	return c.listBlocked.CallUnary(ctx, req)
}

// AdminHandler is an implementation of the openotters.holt.v1.Admin service.
type AdminHandler interface {
	ListTunnels(context.Context, *connect.Request[v1.ListTunnelsRequest]) (*connect.Response[v1.ListTunnelsResponse], error)
	StopTunnel(context.Context, *connect.Request[v1.StopTunnelRequest]) (*connect.Response[v1.StopTunnelResponse], error)
	// BlockPeer stops a peer's tunnel AND bans its peer id, so it cannot
	// reconnect even with a valid token — versus StopTunnel's plain
	// disconnect. The ban is on the identity, not one specific token:
	// every token whose subject is that id (including ones minted while
	// blocked) is refused until UnblockPeer. Requires the hub to have a
	// blocker configured; otherwise returns Unimplemented.
	BlockPeer(context.Context, *connect.Request[v1.BlockPeerRequest]) (*connect.Response[v1.BlockPeerResponse], error)
	// UnblockPeer lifts a BlockPeer ban so the peer may reconnect. Tokens
	// minted before the block that have not expired become valid again;
	// blocking never invalidates the tokens themselves.
	UnblockPeer(context.Context, *connect.Request[v1.UnblockPeerRequest]) (*connect.Response[v1.UnblockPeerResponse], error)
	// ListBlocked returns the currently-blocked peers (which have no
	// live tunnel to appear in ListTunnels). Empty when no blocker is
	// configured.
	ListBlocked(context.Context, *connect.Request[v1.ListBlockedRequest]) (*connect.Response[v1.ListBlockedResponse], error)
}

// NewAdminHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminHandler(svc AdminHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminMethods := v1.File_v1_admin_proto.Services().ByName("Admin").Methods()
	adminListTunnelsHandler := connect.NewUnaryHandler(
		AdminListTunnelsProcedure,
		svc.ListTunnels,
		connect.WithSchema(adminMethods.ByName("ListTunnels")),
		connect.WithHandlerOptions(opts...),
	)
	adminStopTunnelHandler := connect.NewUnaryHandler(
		AdminStopTunnelProcedure,
		svc.StopTunnel,
		connect.WithSchema(adminMethods.ByName("StopTunnel")),
		connect.WithHandlerOptions(opts...),
	)
	adminBlockPeerHandler := connect.NewUnaryHandler(
		AdminBlockPeerProcedure,
		svc.BlockPeer,
		connect.WithSchema(adminMethods.ByName("BlockPeer")),
		connect.WithHandlerOptions(opts...),
	)
	adminUnblockPeerHandler := connect.NewUnaryHandler(
		AdminUnblockPeerProcedure,
		svc.UnblockPeer,
		connect.WithSchema(adminMethods.ByName("UnblockPeer")),
		connect.WithHandlerOptions(opts...),
	)
	adminListBlockedHandler := connect.NewUnaryHandler(
		AdminListBlockedProcedure,
		svc.ListBlocked,
		connect.WithSchema(adminMethods.ByName("ListBlocked")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openotters.holt.v1.Admin/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminListTunnelsProcedure:
			adminListTunnelsHandler.ServeHTTP(w, r)
		case AdminStopTunnelProcedure:
			adminStopTunnelHandler.ServeHTTP(w, r)
		case AdminBlockPeerProcedure:
			adminBlockPeerHandler.ServeHTTP(w, r)
		case AdminUnblockPeerProcedure:
			adminUnblockPeerHandler.ServeHTTP(w, r)
		case AdminListBlockedProcedure:
			adminListBlockedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminHandler struct{}

func (UnimplementedAdminHandler) ListTunnels(context.Context, *connect.Request[v1.ListTunnelsRequest]) (*connect.Response[v1.ListTunnelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.holt.v1.Admin.ListTunnels is not implemented"))
}

func (UnimplementedAdminHandler) StopTunnel(context.Context, *connect.Request[v1.StopTunnelRequest]) (*connect.Response[v1.StopTunnelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.holt.v1.Admin.StopTunnel is not implemented"))
}

func (UnimplementedAdminHandler) BlockPeer(context.Context, *connect.Request[v1.BlockPeerRequest]) (*connect.Response[v1.BlockPeerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.holt.v1.Admin.BlockPeer is not implemented"))
}

func (UnimplementedAdminHandler) UnblockPeer(context.Context, *connect.Request[v1.UnblockPeerRequest]) (*connect.Response[v1.UnblockPeerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.holt.v1.Admin.UnblockPeer is not implemented"))
}

func (UnimplementedAdminHandler) ListBlocked(context.Context, *connect.Request[v1.ListBlockedRequest]) (*connect.Response[v1.ListBlockedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.holt.v1.Admin.ListBlocked is not implemented"))
}
