// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/tunnel.proto

package holtv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/openotters/holt/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TunnelName is the fully-qualified name of the Tunnel service.
	TunnelName = "openotters.holt.v1.Tunnel"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TunnelAttachProcedure is the fully-qualified name of the Tunnel's Attach RPC.
	TunnelAttachProcedure = "/openotters.holt.v1.Tunnel/Attach"
)

// TunnelClient is a client for the openotters.holt.v1.Tunnel service.
type TunnelClient interface {
	// Attach opens the reverse tunnel. The peer is the stream client
	// and MUST send Hello as its first frame; the hub replies Welcome
	// (or closes the stream). From then on only data and go_away
	// frames are legal. A second Attach for the same peer replaces the
	// first — the older tunnel is closed with GoAway("superseded") so
	// a crashed-and-redialed peer never waits out a keepalive timeout.
	Attach(context.Context) *connect.BidiStreamForClient[v1.TunnelFrame, v1.TunnelFrame]
}

// NewTunnelClient constructs a client for the openotters.holt.v1.Tunnel service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTunnelClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TunnelClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tunnelMethods := v1.File_v1_tunnel_proto.Services().ByName("Tunnel").Methods()
	return &tunnelClient{
		attach: connect.NewClient[v1.TunnelFrame, v1.TunnelFrame](
			httpClient,
			baseURL+TunnelAttachProcedure,
			connect.WithSchema(tunnelMethods.ByName("Attach")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tunnelClient implements TunnelClient.
type tunnelClient struct {
	attach *connect.Client[v1.TunnelFrame, v1.TunnelFrame]
}

// Attach calls openotters.holt.v1.Tunnel.Attach.
func (c *tunnelClient) Attach(ctx context.Context) *connect.BidiStreamForClient[v1.TunnelFrame, v1.TunnelFrame] {
	return c.attach.CallBidiStream(ctx)
}

// TunnelHandler is an implementation of the openotters.holt.v1.Tunnel service.
type TunnelHandler interface {
	// Attach opens the reverse tunnel. The peer is the stream client
	// and MUST send Hello as its first frame; the hub replies Welcome
	// (or closes the stream). From then on only data and go_away
	// frames are legal. A second Attach for the same peer replaces the
	// first — the older tunnel is closed with GoAway("superseded") so
	// a crashed-and-redialed peer never waits out a keepalive timeout.
	Attach(context.Context, *connect.BidiStream[v1.TunnelFrame, v1.TunnelFrame]) error
}

// NewTunnelHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTunnelHandler(svc TunnelHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tunnelMethods := v1.File_v1_tunnel_proto.Services().ByName("Tunnel").Methods()
	tunnelAttachHandler := connect.NewBidiStreamHandler(
		TunnelAttachProcedure,
		svc.Attach,
		connect.WithSchema(tunnelMethods.ByName("Attach")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openotters.holt.v1.Tunnel/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TunnelAttachProcedure:
			tunnelAttachHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTunnelHandler returns CodeUnimplemented from all methods.
type UnimplementedTunnelHandler struct{}

func (UnimplementedTunnelHandler) Attach(context.Context, *connect.BidiStream[v1.TunnelFrame, v1.TunnelFrame]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("openotters.holt.v1.Tunnel.Attach is not implemented"))
}
