// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/admin.proto

package holtv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Peer           string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	PeerVersion    string                 `protobuf:"bytes,2,opt,name=peer_version,json=peerVersion,proto3" json:"peer_version,omitempty"`
	AttachedAtUnix int64                  `protobuf:"varint,3,opt,name=attached_at_unix,json=attachedAtUnix,proto3" json:"attached_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TunnelInfo) Reset() {
	*x = TunnelInfo{}
	mi := &file_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelInfo) ProtoMessage() {}

func (x *TunnelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelInfo.ProtoReflect.Descriptor instead.
func (*TunnelInfo) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelInfo) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *TunnelInfo) GetPeerVersion() string {
	if x != nil {
		return x.PeerVersion
	}
	return ""
}

func (x *TunnelInfo) GetAttachedAtUnix() int64 {
	if x != nil {
		return x.AttachedAtUnix
	}
	return 0
}

type ListTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsRequest) Reset() {
	*x = ListTunnelsRequest{}
	mi := &file_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsRequest) ProtoMessage() {}

func (x *ListTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{1}
}

type ListTunnelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*TunnelInfo          `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsResponse) Reset() {
	*x = ListTunnelsResponse{}
	mi := &file_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsResponse) ProtoMessage() {}

func (x *ListTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListTunnelsResponse) GetTunnels() []*TunnelInfo {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type StopTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // GoAway reason sent to the peer; default "stopped-by-operator"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTunnelRequest) Reset() {
	*x = StopTunnelRequest{}
	mi := &file_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTunnelRequest) ProtoMessage() {}

func (x *StopTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTunnelRequest.ProtoReflect.Descriptor instead.
func (*StopTunnelRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *StopTunnelRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *StopTunnelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"` // false when no tunnel was attached for that peer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTunnelResponse) Reset() {
	*x = StopTunnelResponse{}
	mi := &file_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTunnelResponse) ProtoMessage() {}

func (x *StopTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTunnelResponse.ProtoReflect.Descriptor instead.
func (*StopTunnelResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *StopTunnelResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type BlockPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPeerRequest) Reset() {
	*x = BlockPeerRequest{}
	mi := &file_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPeerRequest) ProtoMessage() {}

func (x *BlockPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPeerRequest.ProtoReflect.Descriptor instead.
func (*BlockPeerRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *BlockPeerRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

type BlockPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"` // whether a live tunnel was also closed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPeerResponse) Reset() {
	*x = BlockPeerResponse{}
	mi := &file_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPeerResponse) ProtoMessage() {}

func (x *BlockPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPeerResponse.ProtoReflect.Descriptor instead.
func (*BlockPeerResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *BlockPeerResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type UnblockPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockPeerRequest) Reset() {
	*x = UnblockPeerRequest{}
	mi := &file_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockPeerRequest) ProtoMessage() {}

func (x *UnblockPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockPeerRequest.ProtoReflect.Descriptor instead.
func (*UnblockPeerRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UnblockPeerRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

type UnblockPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockPeerResponse) Reset() {
	*x = UnblockPeerResponse{}
	mi := &file_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockPeerResponse) ProtoMessage() {}

func (x *UnblockPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockPeerResponse.ProtoReflect.Descriptor instead.
func (*UnblockPeerResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{8}
}

type BlockedPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	BlockedAtUnix int64                  `protobuf:"varint,2,opt,name=blocked_at_unix,json=blockedAtUnix,proto3" json:"blocked_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockedPeer) Reset() {
	*x = BlockedPeer{}
	mi := &file_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockedPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedPeer) ProtoMessage() {}

func (x *BlockedPeer) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockedPeer.ProtoReflect.Descriptor instead.
func (*BlockedPeer) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *BlockedPeer) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *BlockedPeer) GetBlockedAtUnix() int64 {
	if x != nil {
		return x.BlockedAtUnix
	}
	return 0
}

type ListBlockedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockedRequest) Reset() {
	*x = ListBlockedRequest{}
	mi := &file_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedRequest) ProtoMessage() {}

func (x *ListBlockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedRequest.ProtoReflect.Descriptor instead.
func (*ListBlockedRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{10}
}

type ListBlockedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*BlockedPeer         `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockedResponse) Reset() {
	*x = ListBlockedResponse{}
	mi := &file_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedResponse) ProtoMessage() {}

func (x *ListBlockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedResponse.ProtoReflect.Descriptor instead.
func (*ListBlockedResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListBlockedResponse) GetPeers() []*BlockedPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_v1_admin_proto protoreflect.FileDescriptor

const file_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/admin.proto\x12\x12openotters.holt.v1\"m\n" +
	"\n" +
	"TunnelInfo\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12!\n" +
	"\fpeer_version\x18\x02 \x01(\tR\vpeerVersion\x12(\n" +
	"\x10attached_at_unix\x18\x03 \x01(\x03R\x0eattachedAtUnix\"\x14\n" +
	"\x12ListTunnelsRequest\"O\n" +
	"\x13ListTunnelsResponse\x128\n" +
	"\atunnels\x18\x01 \x03(\v2\x1e.openotters.holt.v1.TunnelInfoR\atunnels\"?\n" +
	"\x11StopTunnelRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\".\n" +
	"\x12StopTunnelResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\"&\n" +
	"\x10BlockPeerRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\"-\n" +
	"\x11BlockPeerResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\"(\n" +
	"\x12UnblockPeerRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\"\x15\n" +
	"\x13UnblockPeerResponse\"I\n" +
	"\vBlockedPeer\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12&\n" +
	"\x0fblocked_at_unix\x18\x02 \x01(\x03R\rblockedAtUnix\"\x14\n" +
	"\x12ListBlockedRequest\"L\n" +
	"\x13ListBlockedResponse\x125\n" +
	"\x05peers\x18\x01 \x03(\v2\x1f.openotters.holt.v1.BlockedPeerR\x05peers2\xde\x03\n" +
	"\x05Admin\x12^\n" +
	"\vListTunnels\x12&.openotters.holt.v1.ListTunnelsRequest\x1a'.openotters.holt.v1.ListTunnelsResponse\x12[\n" +
	"\n" +
	"StopTunnel\x12%.openotters.holt.v1.StopTunnelRequest\x1a&.openotters.holt.v1.StopTunnelResponse\x12X\n" +
	"\tBlockPeer\x12$.openotters.holt.v1.BlockPeerRequest\x1a%.openotters.holt.v1.BlockPeerResponse\x12^\n" +
	"\vUnblockPeer\x12&.openotters.holt.v1.UnblockPeerRequest\x1a'.openotters.holt.v1.UnblockPeerResponse\x12^\n" +
	"\vListBlocked\x12&.openotters.holt.v1.ListBlockedRequest\x1a'.openotters.holt.v1.ListBlockedResponseB*Z(github.com/openotters/holt/api/v1;holtv1b\x06proto3"

var (
	file_v1_admin_proto_rawDescOnce sync.Once
	file_v1_admin_proto_rawDescData []byte
)

func file_v1_admin_proto_rawDescGZIP() []byte {
	file_v1_admin_proto_rawDescOnce.Do(func() {
		file_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_proto_rawDesc), len(file_v1_admin_proto_rawDesc)))
	})
	return file_v1_admin_proto_rawDescData
}

var file_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_admin_proto_goTypes = []any{
	(*TunnelInfo)(nil),          // 0: openotters.holt.v1.TunnelInfo
	(*ListTunnelsRequest)(nil),  // 1: openotters.holt.v1.ListTunnelsRequest
	(*ListTunnelsResponse)(nil), // 2: openotters.holt.v1.ListTunnelsResponse
	(*StopTunnelRequest)(nil),   // 3: openotters.holt.v1.StopTunnelRequest
	(*StopTunnelResponse)(nil),  // 4: openotters.holt.v1.StopTunnelResponse
	(*BlockPeerRequest)(nil),    // 5: openotters.holt.v1.BlockPeerRequest
	(*BlockPeerResponse)(nil),   // 6: openotters.holt.v1.BlockPeerResponse
	(*UnblockPeerRequest)(nil),  // 7: openotters.holt.v1.UnblockPeerRequest
	(*UnblockPeerResponse)(nil), // 8: openotters.holt.v1.UnblockPeerResponse
	(*BlockedPeer)(nil),         // 9: openotters.holt.v1.BlockedPeer
	(*ListBlockedRequest)(nil),  // 10: openotters.holt.v1.ListBlockedRequest
	(*ListBlockedResponse)(nil), // 11: openotters.holt.v1.ListBlockedResponse
}
var file_v1_admin_proto_depIdxs = []int32{
	0,  // 0: openotters.holt.v1.ListTunnelsResponse.tunnels:type_name -> openotters.holt.v1.TunnelInfo
	9,  // 1: openotters.holt.v1.ListBlockedResponse.peers:type_name -> openotters.holt.v1.BlockedPeer
	1,  // 2: openotters.holt.v1.Admin.ListTunnels:input_type -> openotters.holt.v1.ListTunnelsRequest
	3,  // 3: openotters.holt.v1.Admin.StopTunnel:input_type -> openotters.holt.v1.StopTunnelRequest
	5,  // 4: openotters.holt.v1.Admin.BlockPeer:input_type -> openotters.holt.v1.BlockPeerRequest
	7,  // 5: openotters.holt.v1.Admin.UnblockPeer:input_type -> openotters.holt.v1.UnblockPeerRequest
	10, // 6: openotters.holt.v1.Admin.ListBlocked:input_type -> openotters.holt.v1.ListBlockedRequest
	2,  // 7: openotters.holt.v1.Admin.ListTunnels:output_type -> openotters.holt.v1.ListTunnelsResponse
	4,  // 8: openotters.holt.v1.Admin.StopTunnel:output_type -> openotters.holt.v1.StopTunnelResponse
	6,  // 9: openotters.holt.v1.Admin.BlockPeer:output_type -> openotters.holt.v1.BlockPeerResponse
	8,  // 10: openotters.holt.v1.Admin.UnblockPeer:output_type -> openotters.holt.v1.UnblockPeerResponse
	11, // 11: openotters.holt.v1.Admin.ListBlocked:output_type -> openotters.holt.v1.ListBlockedResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_v1_admin_proto_init() }
func file_v1_admin_proto_init() {
	if File_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_proto_rawDesc), len(file_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_proto_goTypes,
		DependencyIndexes: file_v1_admin_proto_depIdxs,
		MessageInfos:      file_v1_admin_proto_msgTypes,
	}.Build()
	File_v1_admin_proto = out.File
	file_v1_admin_proto_goTypes = nil
	file_v1_admin_proto_depIdxs = nil
}
