// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/admin.proto

package holtv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_ListTunnels_FullMethodName = "/openotters.holt.v1.Admin/ListTunnels"
	Admin_StopTunnel_FullMethodName  = "/openotters.holt.v1.Admin/StopTunnel"
	Admin_BlockPeer_FullMethodName   = "/openotters.holt.v1.Admin/BlockPeer"
	Admin_UnblockPeer_FullMethodName = "/openotters.holt.v1.Admin/UnblockPeer"
	Admin_ListBlocked_FullMethodName = "/openotters.holt.v1.Admin/ListBlocked"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Admin is the hub's management surface: enumerate live tunnels and
// force one closed. It reflects the hub Registry over the wire so a
// CLI (or grpcurl) can operate a hub remotely. Mount it behind
// whatever operator auth the deployment uses.
type AdminClient interface {
	ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error)
	StopTunnel(ctx context.Context, in *StopTunnelRequest, opts ...grpc.CallOption) (*StopTunnelResponse, error)
	// BlockPeer stops a peer's tunnel AND blocks its credential so it
	// cannot reconnect — a hard revoke, versus StopTunnel's plain
	// disconnect. Requires the hub to have a blocker configured;
	// otherwise returns Unimplemented.
	BlockPeer(ctx context.Context, in *BlockPeerRequest, opts ...grpc.CallOption) (*BlockPeerResponse, error)
	// UnblockPeer lifts a BlockPeer block so the peer may reconnect.
	UnblockPeer(ctx context.Context, in *UnblockPeerRequest, opts ...grpc.CallOption) (*UnblockPeerResponse, error)
	// ListBlocked returns the currently-blocked peers (which have no
	// live tunnel to appear in ListTunnels). Empty when no blocker is
	// configured.
	ListBlocked(ctx context.Context, in *ListBlockedRequest, opts ...grpc.CallOption) (*ListBlockedResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTunnelsResponse)
	err := c.cc.Invoke(ctx, Admin_ListTunnels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) StopTunnel(ctx context.Context, in *StopTunnelRequest, opts ...grpc.CallOption) (*StopTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTunnelResponse)
	err := c.cc.Invoke(ctx, Admin_StopTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) BlockPeer(ctx context.Context, in *BlockPeerRequest, opts ...grpc.CallOption) (*BlockPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockPeerResponse)
	err := c.cc.Invoke(ctx, Admin_BlockPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UnblockPeer(ctx context.Context, in *UnblockPeerRequest, opts ...grpc.CallOption) (*UnblockPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockPeerResponse)
	err := c.cc.Invoke(ctx, Admin_UnblockPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListBlocked(ctx context.Context, in *ListBlockedRequest, opts ...grpc.CallOption) (*ListBlockedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlockedResponse)
	err := c.cc.Invoke(ctx, Admin_ListBlocked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
//
// Admin is the hub's management surface: enumerate live tunnels and
// force one closed. It reflects the hub Registry over the wire so a
// CLI (or grpcurl) can operate a hub remotely. Mount it behind
// whatever operator auth the deployment uses.
type AdminServer interface {
	ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error)
	StopTunnel(context.Context, *StopTunnelRequest) (*StopTunnelResponse, error)
	// BlockPeer stops a peer's tunnel AND blocks its credential so it
	// cannot reconnect — a hard revoke, versus StopTunnel's plain
	// disconnect. Requires the hub to have a blocker configured;
	// otherwise returns Unimplemented.
	BlockPeer(context.Context, *BlockPeerRequest) (*BlockPeerResponse, error)
	// UnblockPeer lifts a BlockPeer block so the peer may reconnect.
	UnblockPeer(context.Context, *UnblockPeerRequest) (*UnblockPeerResponse, error)
	// ListBlocked returns the currently-blocked peers (which have no
	// live tunnel to appear in ListTunnels). Empty when no blocker is
	// configured.
	ListBlocked(context.Context, *ListBlockedRequest) (*ListBlockedResponse, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTunnels not implemented")
}
func (UnimplementedAdminServer) StopTunnel(context.Context, *StopTunnelRequest) (*StopTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTunnel not implemented")
}
func (UnimplementedAdminServer) BlockPeer(context.Context, *BlockPeerRequest) (*BlockPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockPeer not implemented")
}
func (UnimplementedAdminServer) UnblockPeer(context.Context, *UnblockPeerRequest) (*UnblockPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockPeer not implemented")
}
func (UnimplementedAdminServer) ListBlocked(context.Context, *ListBlockedRequest) (*ListBlockedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlocked not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_ListTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTunnelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListTunnels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListTunnels(ctx, req.(*ListTunnelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_StopTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).StopTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_StopTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).StopTunnel(ctx, req.(*StopTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_BlockPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).BlockPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_BlockPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).BlockPeer(ctx, req.(*BlockPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UnblockPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UnblockPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UnblockPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UnblockPeer(ctx, req.(*UnblockPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListBlocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListBlocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListBlocked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListBlocked(ctx, req.(*ListBlockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openotters.holt.v1.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTunnels",
			Handler:    _Admin_ListTunnels_Handler,
		},
		{
			MethodName: "StopTunnel",
			Handler:    _Admin_StopTunnel_Handler,
		},
		{
			MethodName: "BlockPeer",
			Handler:    _Admin_BlockPeer_Handler,
		},
		{
			MethodName: "UnblockPeer",
			Handler:    _Admin_UnblockPeer_Handler,
		},
		{
			MethodName: "ListBlocked",
			Handler:    _Admin_ListBlocked_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/admin.proto",
}
