// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/admin.proto

package holtv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelEvent_Kind int32

const (
	TunnelEvent_KIND_UNSPECIFIED TunnelEvent_Kind = 0
	TunnelEvent_KIND_ATTACHED    TunnelEvent_Kind = 1
	TunnelEvent_KIND_DETACHED    TunnelEvent_Kind = 2
)

// Enum value maps for TunnelEvent_Kind.
var (
	TunnelEvent_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_ATTACHED",
		2: "KIND_DETACHED",
	}
	TunnelEvent_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_ATTACHED":    1,
		"KIND_DETACHED":    2,
	}
)

func (x TunnelEvent_Kind) Enum() *TunnelEvent_Kind {
	p := new(TunnelEvent_Kind)
	*p = x
	return p
}

func (x TunnelEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_admin_proto_enumTypes[0].Descriptor()
}

func (TunnelEvent_Kind) Type() protoreflect.EnumType {
	return &file_v1_admin_proto_enumTypes[0]
}

func (x TunnelEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelEvent_Kind.Descriptor instead.
func (TunnelEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{13, 0}
}

type TunnelInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Peer           string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	PeerVersion    string                 `protobuf:"bytes,2,opt,name=peer_version,json=peerVersion,proto3" json:"peer_version,omitempty"`
	AttachedAtUnix int64                  `protobuf:"varint,3,opt,name=attached_at_unix,json=attachedAtUnix,proto3" json:"attached_at_unix,omitempty"`
	// What the peer said it carries: "http", "https", or "" from a peer
	// older than the field.
	TunnelType    string `protobuf:"bytes,4,opt,name=tunnel_type,json=tunnelType,proto3" json:"tunnel_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelInfo) Reset() {
	*x = TunnelInfo{}
	mi := &file_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelInfo) ProtoMessage() {}

func (x *TunnelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelInfo.ProtoReflect.Descriptor instead.
func (*TunnelInfo) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelInfo) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *TunnelInfo) GetPeerVersion() string {
	if x != nil {
		return x.PeerVersion
	}
	return ""
}

func (x *TunnelInfo) GetAttachedAtUnix() int64 {
	if x != nil {
		return x.AttachedAtUnix
	}
	return 0
}

func (x *TunnelInfo) GetTunnelType() string {
	if x != nil {
		return x.TunnelType
	}
	return ""
}

type ListTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsRequest) Reset() {
	*x = ListTunnelsRequest{}
	mi := &file_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsRequest) ProtoMessage() {}

func (x *ListTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{1}
}

type ListTunnelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*TunnelInfo          `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsResponse) Reset() {
	*x = ListTunnelsResponse{}
	mi := &file_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsResponse) ProtoMessage() {}

func (x *ListTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListTunnelsResponse) GetTunnels() []*TunnelInfo {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type StopTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // GoAway reason sent to the peer; default "stopped-by-operator"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTunnelRequest) Reset() {
	*x = StopTunnelRequest{}
	mi := &file_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTunnelRequest) ProtoMessage() {}

func (x *StopTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTunnelRequest.ProtoReflect.Descriptor instead.
func (*StopTunnelRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *StopTunnelRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *StopTunnelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"` // false when no tunnel was attached for that peer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTunnelResponse) Reset() {
	*x = StopTunnelResponse{}
	mi := &file_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTunnelResponse) ProtoMessage() {}

func (x *StopTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTunnelResponse.ProtoReflect.Descriptor instead.
func (*StopTunnelResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *StopTunnelResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type BlockPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPeerRequest) Reset() {
	*x = BlockPeerRequest{}
	mi := &file_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPeerRequest) ProtoMessage() {}

func (x *BlockPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPeerRequest.ProtoReflect.Descriptor instead.
func (*BlockPeerRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *BlockPeerRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

type BlockPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"` // whether a live tunnel was also closed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPeerResponse) Reset() {
	*x = BlockPeerResponse{}
	mi := &file_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPeerResponse) ProtoMessage() {}

func (x *BlockPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPeerResponse.ProtoReflect.Descriptor instead.
func (*BlockPeerResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *BlockPeerResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type UnblockPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockPeerRequest) Reset() {
	*x = UnblockPeerRequest{}
	mi := &file_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockPeerRequest) ProtoMessage() {}

func (x *UnblockPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockPeerRequest.ProtoReflect.Descriptor instead.
func (*UnblockPeerRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UnblockPeerRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

type UnblockPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockPeerResponse) Reset() {
	*x = UnblockPeerResponse{}
	mi := &file_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockPeerResponse) ProtoMessage() {}

func (x *UnblockPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockPeerResponse.ProtoReflect.Descriptor instead.
func (*UnblockPeerResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{8}
}

type BlockedPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	BlockedAtUnix int64                  `protobuf:"varint,2,opt,name=blocked_at_unix,json=blockedAtUnix,proto3" json:"blocked_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockedPeer) Reset() {
	*x = BlockedPeer{}
	mi := &file_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockedPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedPeer) ProtoMessage() {}

func (x *BlockedPeer) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockedPeer.ProtoReflect.Descriptor instead.
func (*BlockedPeer) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *BlockedPeer) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *BlockedPeer) GetBlockedAtUnix() int64 {
	if x != nil {
		return x.BlockedAtUnix
	}
	return 0
}

type ListBlockedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockedRequest) Reset() {
	*x = ListBlockedRequest{}
	mi := &file_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedRequest) ProtoMessage() {}

func (x *ListBlockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedRequest.ProtoReflect.Descriptor instead.
func (*ListBlockedRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{10}
}

type ListBlockedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*BlockedPeer         `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockedResponse) Reset() {
	*x = ListBlockedResponse{}
	mi := &file_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedResponse) ProtoMessage() {}

func (x *ListBlockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedResponse.ProtoReflect.Descriptor instead.
func (*ListBlockedResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListBlockedResponse) GetPeers() []*BlockedPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type WatchTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTunnelsRequest) Reset() {
	*x = WatchTunnelsRequest{}
	mi := &file_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTunnelsRequest) ProtoMessage() {}

func (x *WatchTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTunnelsRequest.ProtoReflect.Descriptor instead.
func (*WatchTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{12}
}

type TunnelEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          TunnelEvent_Kind       `protobuf:"varint,1,opt,name=kind,proto3,enum=openotters.holt.v1.TunnelEvent_Kind" json:"kind,omitempty"`
	Info          *TunnelInfo            `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`     // fully set on ATTACHED; only peer on DETACHED
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // detach reason, empty on ATTACHED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelEvent) Reset() {
	*x = TunnelEvent{}
	mi := &file_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelEvent) ProtoMessage() {}

func (x *TunnelEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelEvent.ProtoReflect.Descriptor instead.
func (*TunnelEvent) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *TunnelEvent) GetKind() TunnelEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return TunnelEvent_KIND_UNSPECIFIED
}

func (x *TunnelEvent) GetInfo() *TunnelInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *TunnelEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type WatchRequestsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only this peer's requests. Empty streams every peer's, which a
	// hub carrying a fleet can make a lot of: a client watching one
	// peer should say so and let the hub do the filtering.
	Peer          string `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequestsRequest) Reset() {
	*x = WatchRequestsRequest{}
	mi := &file_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequestsRequest) ProtoMessage() {}

func (x *WatchRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequestsRequest.ProtoReflect.Descriptor instead.
func (*WatchRequestsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *WatchRequestsRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

// RequestEvent is one request the hub proxied to a peer, reported once
// its response completed. Metadata only: no header values beyond the
// few named here, and never a body.
type RequestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                           // 0 when the request never got a response
	DurationUs    int64                  `protobuf:"varint,5,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"` // microseconds, hub side, tunnel hop included
	AtUnixMillis  int64                  `protobuf:"varint,6,opt,name=at_unix_millis,json=atUnixMillis,proto3" json:"at_unix_millis,omitempty"`
	Query         string                 `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`                              // raw query string, without "?"
	Host          string                 `protobuf:"bytes,8,opt,name=host,proto3" json:"host,omitempty"`                                // authority the request carried
	Proto         string                 `protobuf:"bytes,9,opt,name=proto,proto3" json:"proto,omitempty"`                              // "HTTP/1.1", "HTTP/2.0"
	RemoteAddr    string                 `protobuf:"bytes,10,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"` // who the hub saw connecting
	UserAgent     string                 `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequestBytes  int64                  `protobuf:"varint,12,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`    // declared Content-Length, -1 when unknown
	ResponseBytes int64                  `protobuf:"varint,13,opt,name=response_bytes,json=responseBytes,proto3" json:"response_bytes,omitempty"` // what the peer's handler wrote
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEvent) Reset() {
	*x = RequestEvent{}
	mi := &file_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEvent) ProtoMessage() {}

func (x *RequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEvent.ProtoReflect.Descriptor instead.
func (*RequestEvent) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *RequestEvent) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *RequestEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestEvent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RequestEvent) GetDurationUs() int64 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

func (x *RequestEvent) GetAtUnixMillis() int64 {
	if x != nil {
		return x.AtUnixMillis
	}
	return 0
}

func (x *RequestEvent) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RequestEvent) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RequestEvent) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *RequestEvent) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *RequestEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RequestEvent) GetRequestBytes() int64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *RequestEvent) GetResponseBytes() int64 {
	if x != nil {
		return x.ResponseBytes
	}
	return 0
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{16}
}

type InfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit          string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	Tunnels         int64                  `protobuf:"varint,3,opt,name=tunnels,proto3" json:"tunnels,omitempty"`                                           // live tunnels on this hub
	Blocked         int64                  `protobuf:"varint,4,opt,name=blocked,proto3" json:"blocked,omitempty"`                                           // banned peer ids
	AdvertiseAddr   string                 `protobuf:"bytes,5,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`           // tunnel address stamped into tokens
	ProxyAddr       string                 `protobuf:"bytes,6,opt,name=proxy_addr,json=proxyAddr,proto3" json:"proxy_addr,omitempty"`                       // header-routed proxy
	RouteHeader     string                 `protobuf:"bytes,7,opt,name=route_header,json=routeHeader,proto3" json:"route_header,omitempty"`                 // header naming the target peer
	MetricsAddr     string                 `protobuf:"bytes,8,opt,name=metrics_addr,json=metricsAddr,proto3" json:"metrics_addr,omitempty"`                 // empty when metrics are off
	ExternalUrl     string                 `protobuf:"bytes,9,opt,name=external_url,json=externalUrl,proto3" json:"external_url,omitempty"`                 // public proxy URL, if set
	TokenTtlSeconds int64                  `protobuf:"varint,10,opt,name=token_ttl_seconds,json=tokenTtlSeconds,proto3" json:"token_ttl_seconds,omitempty"` // lifetime of minted tokens
	// How the proxy picks the target peer: "header", "subdomain", or
	// "both". Empty from a hub older than the strategy flag, which
	// always meant header.
	ProxyRouting string `protobuf:"bytes,11,opt,name=proxy_routing,json=proxyRouting,proto3" json:"proxy_routing,omitempty"`
	// Base domain for subdomain routing (<peer>.<domain>), empty when
	// subdomain routing is off.
	ProxyDomain   string `protobuf:"bytes,12,opt,name=proxy_domain,json=proxyDomain,proto3" json:"proxy_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *InfoResponse) GetTunnels() int64 {
	if x != nil {
		return x.Tunnels
	}
	return 0
}

func (x *InfoResponse) GetBlocked() int64 {
	if x != nil {
		return x.Blocked
	}
	return 0
}

func (x *InfoResponse) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *InfoResponse) GetProxyAddr() string {
	if x != nil {
		return x.ProxyAddr
	}
	return ""
}

func (x *InfoResponse) GetRouteHeader() string {
	if x != nil {
		return x.RouteHeader
	}
	return ""
}

func (x *InfoResponse) GetMetricsAddr() string {
	if x != nil {
		return x.MetricsAddr
	}
	return ""
}

func (x *InfoResponse) GetExternalUrl() string {
	if x != nil {
		return x.ExternalUrl
	}
	return ""
}

func (x *InfoResponse) GetTokenTtlSeconds() int64 {
	if x != nil {
		return x.TokenTtlSeconds
	}
	return 0
}

func (x *InfoResponse) GetProxyRouting() string {
	if x != nil {
		return x.ProxyRouting
	}
	return ""
}

func (x *InfoResponse) GetProxyDomain() string {
	if x != nil {
		return x.ProxyDomain
	}
	return ""
}

var File_v1_admin_proto protoreflect.FileDescriptor

const file_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/admin.proto\x12\x12openotters.holt.v1\"\x8e\x01\n" +
	"\n" +
	"TunnelInfo\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12!\n" +
	"\fpeer_version\x18\x02 \x01(\tR\vpeerVersion\x12(\n" +
	"\x10attached_at_unix\x18\x03 \x01(\x03R\x0eattachedAtUnix\x12\x1f\n" +
	"\vtunnel_type\x18\x04 \x01(\tR\n" +
	"tunnelType\"\x14\n" +
	"\x12ListTunnelsRequest\"O\n" +
	"\x13ListTunnelsResponse\x128\n" +
	"\atunnels\x18\x01 \x03(\v2\x1e.openotters.holt.v1.TunnelInfoR\atunnels\"?\n" +
	"\x11StopTunnelRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\".\n" +
	"\x12StopTunnelResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\"&\n" +
	"\x10BlockPeerRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\"-\n" +
	"\x11BlockPeerResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\"(\n" +
	"\x12UnblockPeerRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\"\x15\n" +
	"\x13UnblockPeerResponse\"I\n" +
	"\vBlockedPeer\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12&\n" +
	"\x0fblocked_at_unix\x18\x02 \x01(\x03R\rblockedAtUnix\"\x14\n" +
	"\x12ListBlockedRequest\"L\n" +
	"\x13ListBlockedResponse\x125\n" +
	"\x05peers\x18\x01 \x03(\v2\x1f.openotters.holt.v1.BlockedPeerR\x05peers\"\x15\n" +
	"\x13WatchTunnelsRequest\"\xd7\x01\n" +
	"\vTunnelEvent\x128\n" +
	"\x04kind\x18\x01 \x01(\x0e2$.openotters.holt.v1.TunnelEvent.KindR\x04kind\x122\n" +
	"\x04info\x18\x02 \x01(\v2\x1e.openotters.holt.v1.TunnelInfoR\x04info\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"B\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rKIND_ATTACHED\x10\x01\x12\x11\n" +
	"\rKIND_DETACHED\x10\x02\"*\n" +
	"\x14WatchRequestsRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\"\xf9\x02\n" +
	"\fRequestEvent\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1f\n" +
	"\vduration_us\x18\x05 \x01(\x03R\n" +
	"durationUs\x12$\n" +
	"\x0eat_unix_millis\x18\x06 \x01(\x03R\fatUnixMillis\x12\x14\n" +
	"\x05query\x18\a \x01(\tR\x05query\x12\x12\n" +
	"\x04host\x18\b \x01(\tR\x04host\x12\x14\n" +
	"\x05proto\x18\t \x01(\tR\x05proto\x12\x1f\n" +
	"\vremote_addr\x18\n" +
	" \x01(\tR\n" +
	"remoteAddr\x12\x1d\n" +
	"\n" +
	"user_agent\x18\v \x01(\tR\tuserAgent\x12#\n" +
	"\rrequest_bytes\x18\f \x01(\x03R\frequestBytes\x12%\n" +
	"\x0eresponse_bytes\x18\r \x01(\x03R\rresponseBytes\"\r\n" +
	"\vInfoRequest\"\x97\x03\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x18\n" +
	"\atunnels\x18\x03 \x01(\x03R\atunnels\x12\x18\n" +
	"\ablocked\x18\x04 \x01(\x03R\ablocked\x12%\n" +
	"\x0eadvertise_addr\x18\x05 \x01(\tR\radvertiseAddr\x12\x1d\n" +
	"\n" +
	"proxy_addr\x18\x06 \x01(\tR\tproxyAddr\x12!\n" +
	"\froute_header\x18\a \x01(\tR\vrouteHeader\x12!\n" +
	"\fmetrics_addr\x18\b \x01(\tR\vmetricsAddr\x12!\n" +
	"\fexternal_url\x18\t \x01(\tR\vexternalUrl\x12*\n" +
	"\x11token_ttl_seconds\x18\n" +
	" \x01(\x03R\x0ftokenTtlSeconds\x12#\n" +
	"\rproxy_routing\x18\v \x01(\tR\fproxyRouting\x12!\n" +
	"\fproxy_domain\x18\f \x01(\tR\vproxyDomain2\xe4\x05\n" +
	"\x05Admin\x12^\n" +
	"\vListTunnels\x12&.openotters.holt.v1.ListTunnelsRequest\x1a'.openotters.holt.v1.ListTunnelsResponse\x12[\n" +
	"\n" +
	"StopTunnel\x12%.openotters.holt.v1.StopTunnelRequest\x1a&.openotters.holt.v1.StopTunnelResponse\x12X\n" +
	"\tBlockPeer\x12$.openotters.holt.v1.BlockPeerRequest\x1a%.openotters.holt.v1.BlockPeerResponse\x12^\n" +
	"\vUnblockPeer\x12&.openotters.holt.v1.UnblockPeerRequest\x1a'.openotters.holt.v1.UnblockPeerResponse\x12^\n" +
	"\vListBlocked\x12&.openotters.holt.v1.ListBlockedRequest\x1a'.openotters.holt.v1.ListBlockedResponse\x12Z\n" +
	"\fWatchTunnels\x12'.openotters.holt.v1.WatchTunnelsRequest\x1a\x1f.openotters.holt.v1.TunnelEvent0\x01\x12]\n" +
	"\rWatchRequests\x12(.openotters.holt.v1.WatchRequestsRequest\x1a .openotters.holt.v1.RequestEvent0\x01\x12I\n" +
	"\x04Info\x12\x1f.openotters.holt.v1.InfoRequest\x1a .openotters.holt.v1.InfoResponseB*Z(github.com/openotters/holt/api/v1;holtv1b\x06proto3"

var (
	file_v1_admin_proto_rawDescOnce sync.Once
	file_v1_admin_proto_rawDescData []byte
)

func file_v1_admin_proto_rawDescGZIP() []byte {
	file_v1_admin_proto_rawDescOnce.Do(func() {
		file_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_proto_rawDesc), len(file_v1_admin_proto_rawDesc)))
	})
	return file_v1_admin_proto_rawDescData
}

var file_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_v1_admin_proto_goTypes = []any{
	(TunnelEvent_Kind)(0),        // 0: openotters.holt.v1.TunnelEvent.Kind
	(*TunnelInfo)(nil),           // 1: openotters.holt.v1.TunnelInfo
	(*ListTunnelsRequest)(nil),   // 2: openotters.holt.v1.ListTunnelsRequest
	(*ListTunnelsResponse)(nil),  // 3: openotters.holt.v1.ListTunnelsResponse
	(*StopTunnelRequest)(nil),    // 4: openotters.holt.v1.StopTunnelRequest
	(*StopTunnelResponse)(nil),   // 5: openotters.holt.v1.StopTunnelResponse
	(*BlockPeerRequest)(nil),     // 6: openotters.holt.v1.BlockPeerRequest
	(*BlockPeerResponse)(nil),    // 7: openotters.holt.v1.BlockPeerResponse
	(*UnblockPeerRequest)(nil),   // 8: openotters.holt.v1.UnblockPeerRequest
	(*UnblockPeerResponse)(nil),  // 9: openotters.holt.v1.UnblockPeerResponse
	(*BlockedPeer)(nil),          // 10: openotters.holt.v1.BlockedPeer
	(*ListBlockedRequest)(nil),   // 11: openotters.holt.v1.ListBlockedRequest
	(*ListBlockedResponse)(nil),  // 12: openotters.holt.v1.ListBlockedResponse
	(*WatchTunnelsRequest)(nil),  // 13: openotters.holt.v1.WatchTunnelsRequest
	(*TunnelEvent)(nil),          // 14: openotters.holt.v1.TunnelEvent
	(*WatchRequestsRequest)(nil), // 15: openotters.holt.v1.WatchRequestsRequest
	(*RequestEvent)(nil),         // 16: openotters.holt.v1.RequestEvent
	(*InfoRequest)(nil),          // 17: openotters.holt.v1.InfoRequest
	(*InfoResponse)(nil),         // 18: openotters.holt.v1.InfoResponse
}
var file_v1_admin_proto_depIdxs = []int32{
	1,  // 0: openotters.holt.v1.ListTunnelsResponse.tunnels:type_name -> openotters.holt.v1.TunnelInfo
	10, // 1: openotters.holt.v1.ListBlockedResponse.peers:type_name -> openotters.holt.v1.BlockedPeer
	0,  // 2: openotters.holt.v1.TunnelEvent.kind:type_name -> openotters.holt.v1.TunnelEvent.Kind
	1,  // 3: openotters.holt.v1.TunnelEvent.info:type_name -> openotters.holt.v1.TunnelInfo
	2,  // 4: openotters.holt.v1.Admin.ListTunnels:input_type -> openotters.holt.v1.ListTunnelsRequest
	4,  // 5: openotters.holt.v1.Admin.StopTunnel:input_type -> openotters.holt.v1.StopTunnelRequest
	6,  // 6: openotters.holt.v1.Admin.BlockPeer:input_type -> openotters.holt.v1.BlockPeerRequest
	8,  // 7: openotters.holt.v1.Admin.UnblockPeer:input_type -> openotters.holt.v1.UnblockPeerRequest
	11, // 8: openotters.holt.v1.Admin.ListBlocked:input_type -> openotters.holt.v1.ListBlockedRequest
	13, // 9: openotters.holt.v1.Admin.WatchTunnels:input_type -> openotters.holt.v1.WatchTunnelsRequest
	15, // 10: openotters.holt.v1.Admin.WatchRequests:input_type -> openotters.holt.v1.WatchRequestsRequest
	17, // 11: openotters.holt.v1.Admin.Info:input_type -> openotters.holt.v1.InfoRequest
	3,  // 12: openotters.holt.v1.Admin.ListTunnels:output_type -> openotters.holt.v1.ListTunnelsResponse
	5,  // 13: openotters.holt.v1.Admin.StopTunnel:output_type -> openotters.holt.v1.StopTunnelResponse
	7,  // 14: openotters.holt.v1.Admin.BlockPeer:output_type -> openotters.holt.v1.BlockPeerResponse
	9,  // 15: openotters.holt.v1.Admin.UnblockPeer:output_type -> openotters.holt.v1.UnblockPeerResponse
	12, // 16: openotters.holt.v1.Admin.ListBlocked:output_type -> openotters.holt.v1.ListBlockedResponse
	14, // 17: openotters.holt.v1.Admin.WatchTunnels:output_type -> openotters.holt.v1.TunnelEvent
	16, // 18: openotters.holt.v1.Admin.WatchRequests:output_type -> openotters.holt.v1.RequestEvent
	18, // 19: openotters.holt.v1.Admin.Info:output_type -> openotters.holt.v1.InfoResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_v1_admin_proto_init() }
func file_v1_admin_proto_init() {
	if File_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_proto_rawDesc), len(file_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_proto_goTypes,
		DependencyIndexes: file_v1_admin_proto_depIdxs,
		EnumInfos:         file_v1_admin_proto_enumTypes,
		MessageInfos:      file_v1_admin_proto_msgTypes,
	}.Build()
	File_v1_admin_proto = out.File
	file_v1_admin_proto_goTypes = nil
	file_v1_admin_proto_depIdxs = nil
}
