// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/tunnel.proto

package holtv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TunnelFrame_Hello
	//	*TunnelFrame_Welcome
	//	*TunnelFrame_Data
	//	*TunnelFrame_GoAway
	Kind          isTunnelFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelFrame) Reset() {
	*x = TunnelFrame{}
	mi := &file_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelFrame) ProtoMessage() {}

func (x *TunnelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelFrame.ProtoReflect.Descriptor instead.
func (*TunnelFrame) Descriptor() ([]byte, []int) {
	return file_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelFrame) GetKind() isTunnelFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TunnelFrame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*TunnelFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *TunnelFrame) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Kind.(*TunnelFrame_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *TunnelFrame) GetData() []byte {
	if x != nil {
		if x, ok := x.Kind.(*TunnelFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TunnelFrame) GetGoAway() *GoAway {
	if x != nil {
		if x, ok := x.Kind.(*TunnelFrame_GoAway); ok {
			return x.GoAway
		}
	}
	return nil
}

type isTunnelFrame_Kind interface {
	isTunnelFrame_Kind()
}

type TunnelFrame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // peer → hub; must be the first frame
}

type TunnelFrame_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,2,opt,name=welcome,proto3,oneof"` // hub → peer; must be the first reply
}

type TunnelFrame_Data struct {
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof"` // raw tunnel bytes, at most 32 KiB per frame
}

type TunnelFrame_GoAway struct {
	GoAway *GoAway `protobuf:"bytes,4,opt,name=go_away,json=goAway,proto3,oneof"` // graceful detach, either direction
}

func (*TunnelFrame_Hello) isTunnelFrame_Kind() {}

func (*TunnelFrame_Welcome) isTunnelFrame_Kind() {}

func (*TunnelFrame_Data) isTunnelFrame_Kind() {}

func (*TunnelFrame_GoAway) isTunnelFrame_Kind() {}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // tunnel framing version; currently 1
	PeerVersion     string                 `protobuf:"bytes,2,opt,name=peer_version,json=peerVersion,proto3" json:"peer_version,omitempty"`              // peer build version, observability only
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetPeerVersion() string {
	if x != nil {
		return x.PeerVersion
	}
	return ""
}

type Welcome struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // version the hub selected (≤ offered)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_v1_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *Welcome) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type GoAway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "superseded"     a newer Attach for the same peer replaced this
	//
	//	tunnel; terminal — another instance owns the
	//	peer now (redialing would steal it back)
	//
	// "token-revoked"  the peer's credential was revoked; terminal —
	//
	//	do not redial with the same credential
	//
	// "shutting-down"  hub is draining; redial with backoff
	// "peer-stopping"  deliberate stop; do not redial
	//
	// Applications may define further reasons; unknown reasons are
	// non-terminal (the peer redials with backoff).
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoAway) Reset() {
	*x = GoAway{}
	mi := &file_v1_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoAway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoAway) ProtoMessage() {}

func (x *GoAway) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoAway.ProtoReflect.Descriptor instead.
func (*GoAway) Descriptor() ([]byte, []int) {
	return file_v1_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *GoAway) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_v1_tunnel_proto protoreflect.FileDescriptor

const file_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/tunnel.proto\x12\x12openotters.holt.v1\"\xce\x01\n" +
	"\vTunnelFrame\x121\n" +
	"\x05hello\x18\x01 \x01(\v2\x19.openotters.holt.v1.HelloH\x00R\x05hello\x127\n" +
	"\awelcome\x18\x02 \x01(\v2\x1b.openotters.holt.v1.WelcomeH\x00R\awelcome\x12\x14\n" +
	"\x04data\x18\x03 \x01(\fH\x00R\x04data\x125\n" +
	"\ago_away\x18\x04 \x01(\v2\x1a.openotters.holt.v1.GoAwayH\x00R\x06goAwayB\x06\n" +
	"\x04kind\"U\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12!\n" +
	"\fpeer_version\x18\x02 \x01(\tR\vpeerVersion\"4\n" +
	"\aWelcome\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\" \n" +
	"\x06GoAway\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reasonB*Z(github.com/openotters/holt/api/v1;holtv1b\x06proto3"

var (
	file_v1_tunnel_proto_rawDescOnce sync.Once
	file_v1_tunnel_proto_rawDescData []byte
)

func file_v1_tunnel_proto_rawDescGZIP() []byte {
	file_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_tunnel_proto_rawDesc), len(file_v1_tunnel_proto_rawDesc)))
	})
	return file_v1_tunnel_proto_rawDescData
}

var file_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_tunnel_proto_goTypes = []any{
	(*TunnelFrame)(nil), // 0: openotters.holt.v1.TunnelFrame
	(*Hello)(nil),       // 1: openotters.holt.v1.Hello
	(*Welcome)(nil),     // 2: openotters.holt.v1.Welcome
	(*GoAway)(nil),      // 3: openotters.holt.v1.GoAway
}
var file_v1_tunnel_proto_depIdxs = []int32{
	1, // 0: openotters.holt.v1.TunnelFrame.hello:type_name -> openotters.holt.v1.Hello
	2, // 1: openotters.holt.v1.TunnelFrame.welcome:type_name -> openotters.holt.v1.Welcome
	3, // 2: openotters.holt.v1.TunnelFrame.go_away:type_name -> openotters.holt.v1.GoAway
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_tunnel_proto_init() }
func file_v1_tunnel_proto_init() {
	if File_v1_tunnel_proto != nil {
		return
	}
	file_v1_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelFrame_Hello)(nil),
		(*TunnelFrame_Welcome)(nil),
		(*TunnelFrame_Data)(nil),
		(*TunnelFrame_GoAway)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_tunnel_proto_rawDesc), len(file_v1_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_v1_tunnel_proto_depIdxs,
		MessageInfos:      file_v1_tunnel_proto_msgTypes,
	}.Build()
	File_v1_tunnel_proto = out.File
	file_v1_tunnel_proto_goTypes = nil
	file_v1_tunnel_proto_depIdxs = nil
}
